version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.79.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_extended_0.80.0_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_0.80.0_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo 
  post_build:
    commands:
      - aws s3 sync --delete public s3://dukefeb1
      - echo Build completed on `date`